### PR TITLE
replace Arduino strings with std::string in unit tests

### PR DESCRIPTION
**Pull request by PascalGuenther**

### CODE REVIEW

**Comment by platisd** [comment]
I am still reluctant about this. The `solutions` branch is intended to provide solutions for the "standard" tasks, i.e. the various `TODO` statements in the codebase. The `String` replacement task is a _stretch_ task (along with some other tasks, e.g. injecting the `lightsPin` variable etc). The stretch tasks are left up to the ones following the tutorial to implement how they think. It was not my intention to give any guidelines/directions.

Instead I prefer the following: Have the replacement task implemented in your repo and I will put a link to your repository in the [Shared solutions](https://github.com/platisd/reusable-testable-arduino-tutorial#shared-solutions) part of the README, as it was intended to be from the start. How does that sound?

**Comment by PascalGuenther** [comment]
Sounds great :)
I stumbled accross your repo while looking for a solution how to unit test mit own PlatformIO/Arduino lib which uses a ton of strings. The solution in this branch has wroked for me, at least so far, but I think your right that this isn't a general solution. Feel free to add my Repo to the Readme 👍

**Comment by PascalGuenther** [comment]
And thank you for your great work!

**Comment by platisd** [comment]
Glad you understand! :)
Can you merge your string solution to your `master` branch and let me know? Then I can put a link to your repo. :+1:

**Comment by PascalGuenther** [comment]
> Glad you understand! :)
> Can you merge your string solution to your `master` branch and let me know? Then I can put a link to your repo. 👍

Thank you
Fully merged into my solutin branch: https://github.com/PascalGuenther/reusable-testable-arduino-tutorial/tree/solutions

Did you also discover other solutions, besides vector of char?

**Comment by platisd** [comment]
I would actually do it almost in the way you did, but instead of doing this in a header file:

```cpp
#if defined(ARDUINO)
using String = String;
#else
using String = std::string;
#endif
```
I would try to have "my" string implementation (or rather my _abstraction_) in a separate header file and try to do the switch among the platforms on a CMake level (or whatever build system is being used).
For example, I would have a `arduino/MyString.h` that I would make available via CMake for Arduino builds, a `linux/MyString.h` for Linux builds etc.
Then inside `MyString.h` I would have a wrapper class around whatever string implementation I would be using, only exposing the "string operations" I would need. For example, if I wanted to compare for equality, I would overload the equality operator accordingly, if I wanted a substring I'd have a `substring` method etc.
That way my code would be completely unaffected from whatever the string API happens to be on each platform.

What you proposed works perfectly fine for the majority of cases and will work as long as the user uses functions of the Arduino `String` API that happen to be the same as in `std::string`.

**Comment by PascalGuenther** [comment]
Yeah, really depends primarily on personal preference and the scale of the project. On smaller projects, like Arduinos tend to be, I avoid implementing everything on my own if it isn't worth the effort. If the prioject grows lager and there are other contraints such as memory footprint, I would consider a virtual string class too

**Pull request closed without merging**
